name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: set envs
        env:
          NUXT_ENV_CMS_DATOCMS_API_TOKEN: ${{ secrets.NUXT_ENV_CMS_DATOCMS_API_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Generate
        run: npm run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist